version: 2


models:
  - name: stg_clearbit_enrichment_companies
    columns:
        - name: company_enrichment_name
          tests:
              - unique
              - not_null
        - name: company_enrichment_id
          tests:
              - unique
              - not_null
  - name: stg_clearbit_enrichment_contacts
    columns:
        - name: contact_enrichment_id
          description: "Unique identifier of a Harvest time entry, primary key"
          tests:
              - unique
              - not_null
        - name: contact_enrichment_email
          tests:
              - unique
              - not_null
